---

- name: Install nginx
  hosts: all
  become: yes
  tasks:
    - name: Install using apt
      apt:
        name: nginx
        state: present
        update_cache: yes
      
    - name: start service
      service:
        name: nginx
        state: started
        enabled: yes

